

[db]
dir = "./data/db"


[bucket.example]
## one of "git" or "dir"
source = "dir"
local_dir = "./data/dir"


[bucket."git-example"]

source = "git"
local_dir = "./data/git"
git_repo_url = "https://github.com/vdbulcke/confkv.git"
git_username = "oauth2"


